title: Sugnanam Satya Meghana
description: Graduated in 2021 in the stream of CSE in SRKR Engineering College. Currently working in TCS.  
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
